import "./globals.css";

import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Web Designer and Fron-tend Developer from Sri Lanka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Nav /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
